### ISSUE TITLE
Image not pixel-perfect

### ISSUE THREAD

**Issue by tab00** [lrsjng/jquery-qrcode#27]
Some edges inside the rendered QR image are blurred by 1 pixel.

In comparison, google chart generated images have no blurred edges. The URL used was https://chart.googleapis.com/chart?cht=qr&chs=200x200&chld=M|1&chl=abcdefghijklmnopqrstuvwxyz0123456789

See the attached screen capture image.

Code in HTML template:

```
<div id="qrcode"></div>
```

Code in JavaScript helper:

```
$('#qrcode').qrcode({
                "render": "image",
                size: 165,
                text: "abcdefghijklmnopqrstuvwxyz0123456789"
            });
```

![qr code generation comparison 2015-12-25_23-01-23](https://cloud.githubusercontent.com/assets/12715448/12003715/f75298f0-ab5d-11e5-95ba-f77b0b34cff8.png)

Note that google adds a blank frame around the QR code, so the actual QR code dimensions are 165 \* 165 pixels.

**Comment by tab00** [comment]
I've just realized that the width of the blank frame around Google's QR code varies such that its QR code will be pixel-perfect. In the above example the QR code is actually 174 pixels wide. When I change the size to 174 the resulting image no longer has blurred edges:
```
$('#qrcode').qrcode({
                "render": "image",
                size: 174,
                text: "abcdefghijklmnopqrstuvwxyz0123456789"
            });
```

![qr code generation comparison 2015-12-25_23-42-21](https://cloud.githubusercontent.com/assets/12715448/12003805/3f95c9e0-ab61-11e5-8725-c3e1d644da1f.png)

However with different data, e.g. "abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789"
The QR code becomes blurry again, because 174 pixels is no longer the optimal size, whereas Google's QR code size had increased to be optimal.

![qr code generation comparison 2015-12-25_23-48-09](https://cloud.githubusercontent.com/assets/12715448/12003826/0b763be4-ab62-11e5-88c8-ecc5d213a951.png)

So is there any way to always get pixel-perfect QR codes, e.g. by using an outer blank frame like google does?

**Comment by fabdouglas** [comment]
`window.devicePixelRatio` should be used.

**Comment by bhoylloza** [comment]
window.devicePixelRatio should be used.

**Comment by bhoylloza** [comment]
I've just realized that the width of the blank frame around Google's QR code varies such that its QR code will be pixel-perfect. In the above example the QR code is actually 174 pixels wide.

When I change the size to 174 the resulting image no longer has blurred edges:

$('#qrcode').qrcode({
                "render": "image",
                size: 174,
                text: "abcdefghijklmnopqrstuvwxyz0123456789"
            });
qr code generation comparison 2015-12-25_23-42-21

However with different data, e.g. "abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789"
The QR code becomes blurry again, because 174 pixels is no longer the optimal size, whereas Google's QR code size had increased to be optimal.

qr code generation comparison 2015-12-25_23-48-09

So is there any way to always get pixel-perfect QR code images regardless of data amount, e.g. by using an outer blank frame like google does?

**Comment by lrsjng** [comment]
I think I don't put work into that. Have a look at https://larsjung.de/kjua/ for a pixel-perfect solution.
